### ISSUE TITLE
Dealing with monetary values in a React/RN project 

### ISSUE THREAD

**Issue by blefebvre** [OttawaReactJS/talks#10]
I’d like to propose a talk that highlights some of the issues encountered when dealing with monetary (or any floating point) values in an app that uses JavaScript, as well as a handy library I’ve used (Big.js) to work around them.

I can make it on the 25th if you’re still looking for speakers!

**Comment by btav** [comment]
@blefebvre yer confirmed for April's meetup. Excited for the talk 🎉!

**Comment by blefebvre** [comment]
Sounds good, thanks @btav!
