### ISSUE TITLE
Pure Yoga Ottawa - React & Custom CDN & Contentful

### ISSUE THREAD

**Issue by fighella** [OttawaReactJS/talks#14]
I could give a quick talk about how/why I build the local Ottawa Pure Yoga websites on React.

Pulling data from their old CMS and adding Contentful for new content types using Zeit.co and next.js

**Comment by btav** [comment]
@fighella 👍 that sounds like it would be an interesting talk. When would you be available to speak? We have a slot open this month on January 30th (not sure if that is too late notice).

**Comment by fighella** [comment]
I missed this in 2019. Would consider in 2021.
