### ISSUE TITLE
Introduction to TypeScript + React

### ISSUE THREAD

**Issue by blefebvre** [OttawaReactJS/talks#15]
- what’s all the fuss about?
- pros and cons (the TS tax)
- adding TS incrementally to an existing codebase

**Comment by blefebvre** [comment]
hey @ericadamski, will there be a virtual meetup in June? happy to present this topic if so. I've been having fun with a demo app to show off the key concepts.

**Comment by ericadamski** [comment]
@blefebvre we will be having one in June! We'll put you the list 😉

**Comment by blefebvre** [comment]
Sounds good!

**Comment by btav** [comment]
Closing old issue!
