### ISSUE TITLE
Gaging interest in graphQL / type safety 

### ISSUE THREAD

**Issue by PookMook** [OttawaReactJS/talks#17]
Hey, I wondered if some people would be interested in general talk on graphQL, schema driven or code first and a slight touch on type safety it provides? (whether it's in urql or apollo it doesn't really matter) 
It can be angled at pretty much any level of knowledge on graphQL depending if there was talks on it before.

Another version of it could be on the different levels of type safety you can have in a react app, but I see you had a TS presentation recently, so maybe not!
JS
JS + propTypes
JS + JSdocs
JS + TS
TS
TS + GraphQL/JSON-schema

**Comment by btav** [comment]
Closing old issue!
