### ISSUE TITLE
Gaging interest in Design systems

### ISSUE THREAD

**Issue by PookMook** [OttawaReactJS/talks#18]
I've been playing with StitchesJS recently, building a design system for one of our project, and hopefully the company moving forward.
I feel like there's a lot of stuff that we don't consider being part of a design system, like animations, interactions or even DX, and we often summarize it to be just typography and UI.

Could go over the general considerations for design systems, and a bit of live coding using stitches.
Or a full live coding building a dummy design system from scratch and going over those key points along the way

**Comment by matldupont** [comment]
I dig it!!

**Comment by btav** [comment]
Closing old issue!
