### ISSUE TITLE
Pain points using React-Native

### ISSUE THREAD

**Issue by btav** [OttawaReactJS/talks#2]
There have been a few articles that have been released lately discussing how some companies are moving away from React-Native (Airbnb, Udacity, etc).

https://medium.com/airbnb-engineering/react-native-at-airbnb-f95aa460be1c
https://engineering.udacity.com/react-native-a-retrospective-from-the-mobile-engineering-team-at-udacity-89975d6a8102

 I was thinking of doing a talk to give the community context behind the issues that some companies are running into using React-Native. Furthermore, some of my own pain points using react-native for awhile now.

**Comment by matldupont** [comment]
Awesome!

**Comment by sopheap-hok** [comment]
Yes!!! Great topic, I’d love to hear more about it before starting my own side React Native projects.

**Comment by cdtinney** [comment]
This should be closed! Good talk.

**Comment by btav** [comment]
@cdtinney Thanks!
