### ISSUE TITLE
Server Components and the New `app` Folder in Next 13

### ISSUE THREAD

**Issue by move-zig** [OttawaReactJS/talks#20]
Next 13 introduced a new way to structure our projects to take advantage of server components.

**Topics**
- app folder structure
- server components
- fetching data
- mutating data

**Comment by btav** [comment]
I think this would be a great topic. This is something that I am currently learning at work. Would you be interested in giving this talk?

**Comment by move-zig** [comment]
Hi @btav. I won't have time to put this together, but if you or anyone else wants to give it a shot that would be great!

**Comment by btav** [comment]
I can try to prepare something for next meetup!

**Comment by move-zig** [comment]
Great presentation @btav!
