### ISSUE TITLE
Notifications in Progressive Web Apps

### ISSUE THREAD

**Issue by inezabonte** [OttawaReactJS/talks#21]
This may not be a react specific thing but more about the Web API
I feel like Notifications in PWAs are something that are quite under-utilized.
At the moment web-push notifications are fully supported in chrome android.
It's just recently that they got [added to webkit in beta](https://webkit.org/blog/13878/web-push-for-web-apps-on-ios-and-ipados/).
I find this topic very exciting, I'd love to present it.

**Comment by btav** [comment]
Very interesting topic would love to hear more about it! Would you be available to give the talk at next month's meetup? Should either be April 20th or 27th.

**Comment by inezabonte** [comment]
I will be available @btav

**Comment by btav** [comment]
Closing this issue as @inezabonte has presented this talk already! Thanks!
