### ISSUE TITLE
Everything about React keys

### ISSUE THREAD

**Issue by vezaynk** [OttawaReactJS/talks#22]
I have slide deck ready to discuss React's `key` prop in depth which covers:

 - Light overview of React's diffing process
 - What keys do
 - How to use them
 - Discussing common mistakes

Hoping to present it at the next available slot :)

**Comment by btav** [comment]
Sounds like a plan! We are planning the next meetup and I will reach out once we figure out venue, etc.

**Comment by btav** [comment]
Thanks for giving the talk @vezaynk !
