### ISSUE TITLE
Lessons learned by building my own React-like femtoframework

### ISSUE THREAD

**Issue by Xe** [OttawaReactJS/talks#23]
I built my own React clone named [Xeact](https://xeiaso.net/blog/series/xeact) in an effort to write a moderately useful admin UI named DAB (Data About Business) at my last job. It was originally very tongue in cheek and had syntax that only a haskeller could love.

Through some miracle, everything worked and it ended up making DAB one of the most successful frontend projects I, the recovering ex-SRE/backend developer, had ever made. This talk will be covering the overall timeline and usage of Xeact in the wild as well as its acquisition by the Techaro and the future plans for a unified client-server architecture with the power of OLIN technology.

My talk will have at least one joke in it about our industry. Extra credit if you figure out what it is.

**Comment by btav** [comment]
This talk sounds very entertaining @Xe and I'm excited to hear the story! Our next meetup in November is a relaxed end-of-year social gathering and we'll be taking a break in December due to the typically busy holiday season. Would you be interested in presenting at our January meetup?

**Comment by Xe** [comment]
Yep!

**Comment by btav** [comment]
Awesome I will reach out once I have more details on the date/time and location of the meetup! It will most likely be on the third Thursday.

**Comment by Xe** [comment]
Talk is live on my blog, thanks for having me speak! https://xeiaso.net/talks/2024/xeact/
