### ISSUE TITLE
React Composition

### ISSUE THREAD

**Issue by mikedidomizio** [OttawaReactJS/talks#24]
If there's interest, I can present the topic of React Composition.  This will include discussing why, the benefits, how one can transition over incrementally, as well as a short CodeSandbox demo that can be used by others later.

**Comment by btav** [comment]
That sounds great @mikedidomizio! Would you be interested in presenting at June's meetup? (May is most likely going to be a social meetup at a bar)

**Comment by mikedidomizio** [comment]
Hey @btav, June is fine with me!

**Comment by btav** [comment]
Great talk! Closing because this is an old issue. Thanks again @mikedidomizio
