### ISSUE TITLE
Things about being a startup engineer

### ISSUE THREAD

**Issue by ericadamski** [OttawaReactJS/talks#25]
Would love to do a less code focused talk on how to excel as a startup engineer. Some of the things I think would be fun to cover:

* Whats different from larger organizational engineering
* Tools of the trade
* Jack-of-all, master of hopefully one
* How to get in
* How to truely excel
* How to capitalize on the risk
* Trade-offs
* Career planning in startups
* Is it right for me?

**Comment by btav** [comment]
I think this would be a great talk!

**Comment by btav** [comment]
Great talk! Thanks @ericadamski
