### ISSUE TITLE
Blink's fork of WebKit, and how to work effectively in an upstream-downstream relationship

### ISSUE THREAD

**Issue by maruel** [OttawaReactJS/talks#29]
Marc-Antoine Ruel worked on the Google Chrome team from 2007 to 2019. After having improved Chrome's security, done multi-process performance analysis and implemented printing support, in 2008 he started working on the developer infrastructure. In 2013, he was in the front seat to handle Chromium's engine transition from WebKit to Blink. He experienced multiple times an upstream-downstream situation from both sides. Chromium has been used by a amazingly large number non-Google projects since its release in 2008. Then he worked with other projects like Arc from The Browser Company, experiencing the reverse situation.

He may also touch on llama.cpp's usage on downstream projects since it has similar characteristics at a smaller scale.

He'll give a bit of details on the best way to behave as either an upstream or downstream project, and criterias to use to determine if it is better to fork.

**Comment by btav** [comment]
I would love to hear this talk @maruel! Would the September or October meetup work for you? We are still confirming the dates with the venues.

Tentative dates:
- Thursday, September 19th or 26th
- Thursday, October 17th or 24th

Do any of these dates work for you? I will also get back to you once I have more concrete dates from the venues!

**Comment by maruel** [comment]
I'm currently good for any of these dates.

**Comment by btav** [comment]
Really looking forward to this talk. Let's aim for September. I'm just confirming the date with the venue, but tentatively, it's September 19th!

**Comment by maruel** [comment]
I confirm I can do Sept 19th.

**Comment by btav** [comment]
@maruel we got confirmation from Spiria for Sept 19th! We will be opening up RSVPs for the meetup next week.

**Comment by maruel** [comment]
Excellent. What's the primary URL I should share? https://www.meetup.com/ottawa-javascript/events/302544173/ ?

**Comment by btav** [comment]
@maruel haha that is actually a different meetup. I just posted our meetup event -- https://www.meetup.com/ottawa-forwardjs-meetup/events/303130703/

Pls let me know if you would like me to modify the description!

**Comment by maruel** [comment]
Ah! You had mentioned this to me but I still got confused. Dang. Thanks!
Topic title is good.

**Comment by btav** [comment]
Great talk, thanks again @maruel !
