### ISSUE TITLE
React Suspense API, Async Rendering and changes to the lifecycle functions

### ISSUE THREAD

**Issue by matldupont** [OttawaReactJS/talks#3]
With React 17, they'll be introducing the Suspense API and introducing breaking changes with some of the lifecycle functions:
- componentWillMount
- componentWillUpdate
- componentWillReceiveProps 

Introducing: 
- getDerivedStateFromProps
- getSnapshotBeforeUpdate

Getting ahead of the curve with our members would be good.

**Comment by btav** [comment]
Closing old issue!
