### ISSUE TITLE
Introduction to the decentralized web

### ISSUE THREAD

**Issue by RangerMauve** [OttawaReactJS/talks#30]
The web is currently based on HTTP and it's client-server foundations, but there's other ways for data to be published and seen by users. This talk will go over how we can have a more resilient foundation for the web using peer to peer file transfer protocols like IPFS or Hypercore Protocol. We will also go over some easy to use tools for publishers and readers as well as app developers.

---

I've run a similar talk in past JS meetups and at a few conferences but there's been some changes in the space over the past few years. https://getdweb.net/

**Comment by btav** [comment]
Hey @RangerMauve sorry for the delayed response!

Would love to hear this talk at our meetup! We have an upcoming meetup on November 21st, or we could pencil in this talk for sometime in the new year. We're taking December off.

**Comment by RangerMauve** [comment]
Yeah 21st sounds perfect :) I'll put something together for then!

**Comment by btav** [comment]
Great talk! Thanks again @RangerMauve!
