### ISSUE TITLE
Structuring a project as a monorepo

### ISSUE THREAD

**Issue by move-zig** [OttawaReactJS/talks#7]
This isn't strictly React related, but I think it's particularly useful for in-house libraries of common React components.

I have a NodeJS REST API that I've split into smaller services running on different ports. Sometimes these services rely on the functionality in another service. Rather than calling an HTTP endpoint, I'd rather avoid the network call and use a function directly. This lead me to publishing private NPM packages for each service and then adding them as dependencies to other projects. When one project is updated, developers have to remember to update the dependencies of related projects and redeploy.

I used a similar setup for an in-house library of React components that I wanted to share across multiple projects.

In both cases, I think a monorepo would work better. I haven't used a monorepo yet, but I'd like to hear from people who have.

**Comment by cdtinney** [comment]
We've started a new monorepo at work using `lerna` to manage NPM packages. Haven't been using it that long but love it already, despite some CI/CD challenges at first.

I'd also like to hear from people who have been using it (or something similar). I'd be open to doing a talk on our usage so far.

**Comment by cdtinney** [comment]
Not yet -- looks cool.

Some lerna monorepos we've used as inspiration/help:

Gatsby - https://github.com/gatsbyjs/gatsby
Babel - https://github.com/babel/babel
Create-React-App - https://github.com/facebook/create-react-app

**Comment by btav** [comment]
@cdtinney Do you want to do a talk this month on monorepos?

**Comment by cdtinney** [comment]
@btav sure, with the disclaimer that we've only been working with it for about a month so my experience is fairly limited.

**Comment by ericadamski** [comment]
I would love to see a talk on this!

**Comment by cdtinney** [comment]
I'm not sure how a talk on this would relate back to React, though..

**Comment by move-zig** [comment]
I have a bunch of React apps that all use a common set of components. Right
now when the common components get updated, I have to publish to NPM and
then run npm update on every project that depends on them. Learning how
others are using lerna/monorepos can help me and others in similar
situations.

React developers and backend developers can also benefit from a monorepo
setup by having all the code in one place.

Like I said in my initial comment, it's not specifically React related, but
it can be particularly usefull.

**Comment by cdtinney** [comment]
Fair enough. I'll incorporate that into the talk.

**Comment by btav** [comment]
@cdtinney would you like to present at this month's meetup?

**Comment by cdtinney** [comment]
@btav I'm no longer in Ottawa unfortunately 👎 

If anyone wants to use the slide-deck I prepared, here it is: https://drive.google.com/open?id=1BIzZhhG-sNapKim59iYgE_mPug50J_P0lLkn-DAbPjY

**Comment by btav** [comment]
@move-zig Interested in giving a talk on Monorepos? You could use @cdtinney's slides or use them as a starting point?

**Comment by move-zig** [comment]
@btav Sorry I don't have the first-hand knowledge needed. I haven't yet worked with monorepos myself.

**Comment by btav** [comment]
Closing old issue!
