### ISSUE TITLE
Getting started with React Native and TypeScript

### ISSUE THREAD

**Issue by blefebvre** [OttawaReactJS/talks#8]
I've recently shipped a side project to the App Store that's built with React Native and TypeScript. In the process of working on it I became a huge fan of both technologies, and found that they work great together.

I'd like to propose a talk that walks through how to get started building your own RN + TypeScript app, and illustrate my development workflow with some live coding. 

The TypeScript principles would be applicable to folks building web-based React apps as well.

I shared a blog post on this topic recently, and my talk would follow a similar structure: https://brucelefebvre.com/blog/2018/10/12/react-native-typescript-cocoapods/

**Comment by btav** [comment]
I'm very interested! @blefebvre would you like to present at this month's meetup?

**Comment by fighella** [comment]
Definitely interested. :) Jonny

**Comment by btav** [comment]
Sounds good @blefebvre looking forward to it! See ya next year 🎉 !

**Comment by blefebvre** [comment]
Hey @btav, I see that the January meetup date is now set for the 31st. I have a conflict that week unfortunately - would it throw a wrench in things for you if I were to postpone this talk until February?

**Comment by btav** [comment]
Not a problem @blefebvre!

**Comment by btav** [comment]
@blefebvre are you able to present this month?

**Comment by blefebvre** [comment]
@btav, for sure! Looking forward to it. 

What should be my target in terms of talk length? 15 min?

**Comment by btav** [comment]
15 mins sounds great! Thanks looking forward to it!
