### ISSUE TITLE
Using the new hooks API

### ISSUE THREAD

**Issue by mkallies** [OttawaReactJS/talks#9]
Next version of React should be coming with hooks!  Someone should show us how cool they are!

**Comment by fighella** [comment]
I agree.:)

**Comment by btav** [comment]
Great idea! @mkallies or @fighella would one of you like to do a talk? Or perhaps anyone in @OttawaReactJS/organizers interested?

**Comment by mkallies** [comment]
Sure, I'll take a stab at it

**Comment by btav** [comment]
@mkallies Would you like to present at this month's meetup (Jan 31st) or a future one?

**Comment by matldupont** [comment]
lol he'll do it on the 31st @btav

**Comment by matldupont** [comment]
Great talk! @mkallies
